version: "2"
services:

    local-external:
        build: .
        ports:
            - "8083:8080"
        environment: 
            - ENV=external
        networks:
            - internal_network

    local-internal:
        build: .
        ports:
            - "8084:8080"
        environment: 
            - ENV=internal
        networks:
            - internal_network

networks:
    internal_network: